[package]
name = "folo"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
folo_decl_macros = { path = "../folo_decl_macros", version = "0.1.0-main" }
folo_proc_macros = { path = "../folo_proc_macros", version = "0.1.0-main" }
futures = { version = "0.3", default-features = false, features = [
    "std",
    "alloc",
] }
negative-impl = "0.1"
oneshot = "0.1"
pin-project = "1"
thiserror = "1"
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = "0.3"